services:
  - type: web
    name: expense-tracker-backend
    env: node
    plan: free
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DEFAULT_TIMEZONE
        value: Asia/Kolkata
      - key: JWT_EXPIRES_IN
        value: 30d
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: CLIENT_URL
        sync: false
